### ISSUE TITLE
Prueba 1

### ISSUE THREAD

**Issue by nbxandresvejar** [LDFerrer/neubox-challenges#1]
Resultados: José Damián
Ciclo: 1

Problema 1: PHP
Los archivos de entrada se encuentran fijos, lo que no es una buena práctica de programación y no permite realizar más pruebas que la de los archivos dentro del mismo repo.

Problema 2: PHP
Los ruta del archivo de entrada se encuentran fija
Revisando el problema, la forma en como se determina al ganador no es correcta

Problema 2: Js
Los ruta de directorios para el archivo de entrada se encuentran fija, aún cuando se recibe el parametro marca error al abrir archivo
Error: ENOENT: no such file or directory, open 
Emitted 'error' event on Interface instance at:
    at ReadStream.onerror (node:readline:265:10)
    at ReadStream.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open'
}

La forma en como se determina al ganador no es correcta, es necesario revisar nuevamente el problema.

**Comment by LDFerrer** [comment]
Problema 1: PHP. @nbxandresvejar 

@Solución: En el commit [b239b90166683b0af1f529ba571ba7805c1c9b0d] agregué parámetros modificadores, todos son soportados por línea de comandos o URL (GET) por igual (aunque obviamente no ambos a la ves).

#### Parametros modificadores: ###
	/*	Desde línea de comandos y parametros de URL (GET):
	 *	 -f, --folder:		Directorio de trabajo.
	 *	 -b, --book:		Libro de instrucciones.
	 *	 -i, --input-file:	Archivo de entrada.
	 *	 -o, --output-file:	Archivo de salida.
	 *	 -p, --print:		¿Imprimir salida?.
	*/

**Comment by LDFerrer** [comment]
*** # COMENTARIO: @nbxandresvejar Respecto al problema 2, entendí que el método para determinar al ganador es:

1. Se calcula delta para cada ronda.
2. Se busca max( Δ ) en las rondas ganadas de cada jugador.
3. El jugador con max( Δ ) mas alto, es el ganador.

Inicialmente pensé en hacer una sumatoria de los diferenciales de cada ronda ganada de cada jugador, algo como:
    Jx Σ [ max( Δ ): { R1, Rn } ]

Pero el PDF dice que gana el que obtuvo la máxima ventaja (58), pero si aplicaba esa lógica, la diferencia es 60 (que no se relaciona con ese 58 del ejemplo).

¿Podrías orientarme un poco mas?, ¿O mi error es en otra parte?

**Comment by LDFerrer** [comment]
Bueno, en el correo nos daban 48 horas para terminar, y lo recibí jue, 17 mar, 17:10 así que decidí hacer algunas modificaciones según el Ciclo 1 de obsevaciones.

Implementé algo parecido a lo que originalmente intuí:

* Por cada jugador, sumar el diferencial de puntos en sus rondas ganadas desde R1 hasta N rondas.

Ahora gana el que haya sumado mas puntos de rondas ganadas, oséa, gana el que obtuvo la mayor ventaja.
